# Generated by Django 3.1.2 on 2020-12-07 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='connet_time',
            new_name='connect_time',
        ),
    ]
